# Generated by Django 3.0.7 on 2020-08-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_appsettings_server_hostname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='include_all_in_array',
            field=models.BooleanField(default=False, verbose_name='リスト形式のものは繋げて出力する'),
        ),
        migrations.AlterField(
            model_name='user',
            name='paid',
            field=models.BooleanField(default=True),
        ),
    ]
